matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd back-end
      script:
        - gradle build --scan -s
        - gradle check --info
        - gradle jacocoTestReport
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    - language: node_js
      node_js:
        - "node"
      before_script:
        - cd front-end
        - npm install
      cache:
        directories:
          - "node_modules"
      script:
        - npm test --coverage
